server:
  port: 9999 #项目启动访问端口
spring:
  application:
    name: educational
  datasource: #连接数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/educational-administration?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
  servlet:
    multipart: #文件上传配置
      max-file-size: 10MB
      max-request-size: 50MB
  mvc:
      hiddenmethod:
        filter:
          enabled: true

mybatis:
  # model的包
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zijin.educationaladministration.domain
  configuration:
    map-underscore-to-camel-case: true
projectName: educational-administration







